/*
KANTE
Abwassertechnische Anlagen gem. Arbeitshilfen Abwasser (http://www.arbeitshilfen-abwasser.de/html/ISYBAU_Austauschformate_Abwasser.14.08.html)
Haltung (H), Leitung (L), Rinne (RI), Gerinne (GE)
*/

-- Erstellung der Views in separatem Schema zum Schutz bei GMLAS Import -overwrite
--CREATE SCHEMA qgisybau;

-- H Haltung
CREATE OR REPLACE VIEW qgisybau.v_kante_haltung AS 
 SELECT a.ogc_fid,
    a.ogr_pkid,
    a.parent_ogr_pkid,
    a.objektbezeichnung,
    a.objektart,
    a.alteobjektbezeichnung,
    a.lisa_guid,
    a.reihenfolgeid,
    a.status,
    a.baujahr,
    a.entwaesserungsart,
    a.kommentar,
    a.kante_kantentyp,
    a.kante_knotenzulauf,
    a.kante_knotenzulauftyp,
    a.kante_knotenablauf,
    a.kante_knotenablauftyp,
    a.kante_sohlhoehezulauf,
    a.kante_sohlhoeheablauf,
    a.kante_strang,
    a.kante_laenge,
    a.kante_material,
    a.kante_profil_sonderprofilvorhanden,
    a.kante_profil_profilart,
    a.kante_profil_profilid,
    a.kante_profil_profilbreite,
    a.kante_profil_profilhoehe,
    a.kante_haltung_haltungsfunktion,
    a.kante_haltung_dmplaenge,
    a.kante_haltung_rohrlaenge,
    a.kante_haltung_innenschutz,
    a.kante_haltung_auskleidung,
    a.kante_haltung_materialauskleidung,
    a.kante_haltung_nenndruck,
    a.kante_haltung_druckverfahren,
    a.kante_haltung_anschlussdaten_objektbezeichnung,
    a.kante_haltung_anschlussdaten_kantentyp,
    a.kante_haltung_anschlussdaten_entfernung,
    a.kante_haltung_anschlussdaten_anschlussart,
    a.kante_haltung_anschlussdaten_fixierung,
    a.kante_haltung_anschlussdaten_kommentar,
    a.lage_strassenschluessel,
    a.lage_strassenname,
    a.lage_ortsteilschluessel,
    a.lage_ortsteilname,
    a.lage_lageoberflaeche,
    a.lage_kommentarlage,
    a.lage_ueberschwemmungsgebiet,
    a.umweltparameter_abwasserart,
    a.umweltparameter_abwasserartwgs,
    a.umweltparameter_gwabstand,
    a.umweltparameter_wasserschutzzone,
    a.umweltparameter_bodenart,
    a.geometrie_vorlaeufigebezeichnung,
    a.geometrie_geoobjektart,
    a.geometrie_geoobjekttyp,
    a.geometrie_lagegenauigkeitsklasse,
    a.geometrie_hoehengenauigkeitsklasse,
    a.geometrie_datenherkunft,
    a.geometrie_kommentar,
    a.geometrie_crslage,
    a.sanierung_artmassnahme,
    l.l_geom_2d AS geom
   FROM isybau.identifikati_datenkollekti_stammdatenkol_abwassertechnanlage a
     JOIN qgisybau.v_liniengeometrien l ON a.ogr_pkid::text = l.parent_ogr_pkid::text
  WHERE a.objektart = 1 -- G100 1=Kante
    AND a.kante_kantentyp = 0; -- G200 0=Haltung

-- L Leitung
CREATE OR REPLACE VIEW isybau.v_kante_leitung AS 
 SELECT a.ogc_fid,
    a.ogr_pkid,
    a.parent_ogr_pkid,
    a.objektbezeichnung,
    a.objektart,
    a.alteobjektbezeichnung,
    a.lisa_guid,
    a.reihenfolgeid,
    a.status,
    a.baujahr,
    a.entwaesserungsart,
    a.kommentar,
    a.kante_kantentyp,
    a.kante_knotenzulauf,
    a.kante_knotenzulauftyp,
    a.kante_knotenablauf,
    a.kante_knotenablauftyp,
    a.kante_sohlhoehezulauf,
    a.kante_sohlhoeheablauf,
    a.kante_strang,
    a.kante_laenge,
    a.kante_material,
    a.kante_profil_sonderprofilvorhanden,
    a.kante_profil_profilart,
    a.kante_profil_profilid,
    a.kante_profil_profilbreite,
    a.kante_profil_profilhoehe,
    a.kante_leitung_leitungsfunktion,
    a.kante_leitung_innenschutz,
    a.kante_leitung_auskleidung,
    a.kante_leitung_materialauskleidung,
    a.kante_leitung_nenndruck,
    a.kante_leitung_druckverfahren,
    a.kante_leitung_anschlussdaten_objektbezeichnung,
    a.kante_leitung_anschlussdaten_kantentyp,
    a.kante_leitung_anschlussdaten_entfernung,
    a.kante_leitung_anschlussdaten_anschlussart,
    a.kante_leitung_anschlussdaten_fixierung,
    a.kante_leitung_anschlussdaten_kommentar,
    a.kante_rinne_rinnenfunktion,
    a.kante_gerinne_gerinnefunktion,
    a.lage_strassenschluessel,
    a.lage_strassenname,
    a.lage_ortsteilschluessel,
    a.lage_ortsteilname,
    a.lage_lageoberflaeche,
    a.lage_kommentarlage,
    a.lage_ueberschwemmungsgebiet,
    a.umweltparameter_abwasserart,
    a.umweltparameter_abwasserartwgs,
    a.umweltparameter_gwabstand,
    a.umweltparameter_wasserschutzzone,
    a.umweltparameter_bodenart,
    a.geometrie_vorlaeufigebezeichnung,
    a.geometrie_geoobjektart,
    a.geometrie_geoobjekttyp,
    a.geometrie_lagegenauigkeitsklasse,
    a.geometrie_hoehengenauigkeitsklasse,
    a.geometrie_datenherkunft,
    a.geometrie_kommentar,
    a.geometrie_crslage,
    a.sanierung_artmassnahme,
    l.l_geom_2d AS geom
   FROM isybau.identifikati_datenkollekti_stammdatenkol_abwassertechnanlage a
     JOIN qgisybau.v_liniengeometrien l ON a.ogr_pkid::text = l.parent_ogr_pkid::text
  WHERE a.objektart = 1 -- G100 1=Kante
    AND a.kante_kantentyp = 1; -- G200 1=Leitung

-- RI Rinne und GE Gerinne
CREATE OR REPLACE VIEW qgisybau.v_kante_rinnen AS 
 SELECT a.ogc_fid,
    a.ogr_pkid,
    a.parent_ogr_pkid,
    a.objektbezeichnung,
    a.objektart,
    a.alteobjektbezeichnung,
    a.lisa_guid,
    a.reihenfolgeid,
    a.status,
    a.baujahr,
    a.entwaesserungsart,
    a.kommentar,
    a.kante_kantentyp,
    a.kante_knotenzulauf,
    a.kante_knotenzulauftyp,
    a.kante_knotenablauf,
    a.kante_knotenablauftyp,
    a.kante_sohlhoehezulauf,
    a.kante_sohlhoeheablauf,
    a.kante_strang,
    a.kante_laenge,
    a.kante_material,
    a.kante_profil_sonderprofilvorhanden,
    a.kante_profil_profilart,
    a.kante_profil_profilid,
    a.kante_profil_profilbreite,
    a.kante_profil_profilhoehe,
    a.kante_rinne_rinnenfunktion,
    a.kante_gerinne_gerinnefunktion,
    a.lage_strassenschluessel,
    a.lage_strassenname,
    a.lage_ortsteilschluessel,
    a.lage_ortsteilname,
    a.lage_lageoberflaeche,
    a.lage_kommentarlage,
    a.lage_ueberschwemmungsgebiet,
    a.umweltparameter_abwasserart,
    a.umweltparameter_abwasserartwgs,
    a.umweltparameter_gwabstand,
    a.umweltparameter_wasserschutzzone,
    a.umweltparameter_bodenart,
    a.geometrie_vorlaeufigebezeichnung,
    a.geometrie_geoobjektart,
    a.geometrie_geoobjekttyp,
    a.geometrie_lagegenauigkeitsklasse,
    a.geometrie_hoehengenauigkeitsklasse,
    a.geometrie_datenherkunft,
    a.geometrie_kommentar,
    a.geometrie_crslage,
    a.sanierung_artmassnahme,
    l.l_geom_2d AS geom
   FROM isybau.identifikati_datenkollekti_stammdatenkol_abwassertechnanlage a
     JOIN qgisybau.v_liniengeometrien l ON a.ogr_pkid::text = l.parent_ogr_pkid::text
  WHERE a.objektart = 1 -- G100 1=Kante
    AND (a.kante_kantentyp = ANY (ARRAY[2, 3])); -- G200 2=Rinne 3=Gerinne
